apiVersion: v1
kind: ConfigMap
metadata:
  name: quote-api-config
  namespace: quote-k8-java
data:
  application.properties: |
    quarkus.application.name=quote-k8-api
    quarkus.http.port=8080
    quarkus.mongodb.connection-string=mongodb://quote-user:ChangeThisPassword123!@mongodb-service:27017/quote-db?authSource=admin
    quarkus.mongodb.database=quote-db
    quarkus.log.category."com.quote".level=INFO
