# Application configuration
quarkus.application.name=quote-k8-api
quarkus.http.port=8080

# MongoDB configuration
quarkus.mongodb.connection-string=mongodb://quote-user:ChangeThisPassword123!@mongodb-service:27017/quote-db?authSource=admin
quarkus.mongodb.database=quote-db

# Logging
quarkus.log.category."com.quote".level=INFO

# OpenAPI
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true

# Dev mode
%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017/quote-db
