# Application configuration
quarkus.application.name=quote-k8-api
quarkus.http.port=8080

# MongoDB configuration
quarkus.mongodb.connection-string=mongodb://quote-user:ChangeThisPassword123!@mongodb-service:27017/quote-db?authSource=admin
quarkus.mongodb.database=quote-db

# Logging
quarkus.log.category."com.quote".level=INFO

# OpenAPI
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true

# Dev mode
%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017/quote-db

# JWT Configuration
mp.jwt.verify.issuer=quote-k8-java
mp.jwt.verify.audience=quote-k8-users
smallrye.jwt.verify.key.location=sign-key.jwk
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.sign.key.location=sign-key.jwk
smallrye.jwt.new-token.signature-algorithm=HS256
smallrye.jwt.new-token.lifespan=3600

# Cors configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization